### ISSUE TITLE
cmake fails

### ISSUE THREAD

**Issue by skypjack** [abeimler/ecs_benchmark#1]
I tried to compile your project, so as to add to the comparison my own entity-component system. I'd like to know how far it is from the other ones in terms of performance.
Anyway, following the instructions in the `README.md` and running the following command:

    cmake -H. -B./build -C./build/CMakeTools/InitializeCache.cmake -DCMAKE_BUILD_TYPE=Release

I got the a lot of warnings and a blocking error, that is:

    CMake Error at libs/entityx2/CMakeLists.txt:81 (add_executable):
      add_executable cannot create target "entity_test" because another target
      with the same name already exists.  The existing target is an executable
      created in source directory
      "my_source_directory".  See documentation
      for policy CMP0002 for more details.
    Call Stack (most recent call first):
      libs/entityx2/CMakeLists.txt:97 (create_test)

**Comment by abeimler** [comment]
I think that's because I have two entityx-libs in use (entityx v1.x and entityx compile-time version) and both create the test target `entity_test`.

Btw. I disable the Tests and shared-lib builds (don't need it and it cause errors like missing dependencies, ...)
(still gets error like `Could NOT find GOOGLETEST (missing:  GOOGLETEST_LIBRARY GOOGLETEST_MAIN_LIBRARY GOOGLEMOCK_LIBRARY GOOGLEMOCK_MAIN_LIBRARY GOOGLETEST_INCLUDE_DIR GOOGLEMOCK_INCLUDE_DIR) ` but still configure/generate the make file)
Just don't try to `make all` or it will try to build all tests and other stuff you may don't need.


To generate the makefile, try this:
```cmake
cmake -H. -B./build -DCMAKE_BUILD_TYPE=Release -DENTITYX_BUILD_TESTING:BOOL="0" -DENTITYX_BUILD_SHARED:BOOL="0" -DBUILD_TESTING:BOOL="0" -DBUILD_SHARED_LIBS:BOOL="0" 
```

_`-C./build/CMakeTools/InitializeCache.cmake` cause the error, I use Visual Code and it's generate the InitializeCache.cmake file_




For the build, try this:
```cmake
cmake --build ./build --target ecs_benchmark
```
(it's an alternative to `cd build && make ecs_benchmark`)

**Comment by skypjack** [comment]
Ok, it works.
I've just seen that you used `eventpp` in your branch `develop`. Sooner or later I'll publish a more complete suite for signal handling with several classes for different purposes.
Meanwhile, I'd like to test my ECS, so... :-)

**Comment by skypjack** [comment]
I copied `entityx2BenchmarkRunner.cpp` and modified it to inroduce benchmarks for my own ECS.
Anyway I'm consistently getting an error out of the linker:

    CMakeFiles/ecs_benchmark.dir/src/enttBenchmarkRunner.cpp.o:(.bss+0x28): multiple definition of `register_53'
    CMakeFiles/ecs_benchmark.dir/src/entityx2BenchmarkRunner.cpp.o:(.bss+0x28): first defined here

Any idea?

**Comment by skypjack** [comment]
I realized that my ECS is faster than entityx2 in almost all the tests, therefore it would worth adding it to the benchmark suite probably.
Anyway, I don't understand how plotting of data works, it ever mixes up the results!!
Is it normal? It there something should I do to get them ordered?

**Comment by abeimler** [comment]
> Anyway, I don't understand how plotting of data works, it ever mixes up the results!!
> Is it normal? It there something should I do to get them ordered?

Yeah you only need run the right benchmarks only, NOT all benchmarks like "entity create" and other benchmarks with the regex ".\*entityx.\*". It will end mixed up. 

I wrote a better how-to in the README.



> I disable artemis for it takes 10 minutes on my laptop.

Yes probably, I had the same "problem", I disabled this test now.


> Anyway, are you interested in adding EnTT to the comparison?

Sure why not, you can do it by your own (and make a pull-request) or make me a little issue (suggestion) and I try take care of it :)
(`EnTT` is header-only and it use is like the other frameworks, should be easy to impl.)

**Comment by skypjack** [comment]
If you prefer, I can open a PR pushing the three files you need to create in `include` and `src`. I already wrote them to test it actually.
Then I can open an issue (suggestion, of course) mentioning the PR. :-)
Would it work better for you?
